/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'Bx:bxsUser': typeof import('~icons/bx/bxs-user')['default']
    'Codicon:chromeClose': typeof import('~icons/codicon/chrome-close')['default']
    'Codicon:chromeMaximize': typeof import('~icons/codicon/chrome-maximize')['default']
    'Codicon:chromeMinimize': typeof import('~icons/codicon/chrome-minimize')['default']
    CopyContainer: typeof import('./src/components/CopyContainer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GlassCard: typeof import('./src/components/GlassCard.vue')['default']
    'Ic:baselineEdit': typeof import('~icons/ic/baseline-edit')['default']
    'Ic:outlineLogout': typeof import('~icons/ic/outline-logout')['default']
    'Ion:drag': typeof import('~icons/ion/drag')['default']
    ItsEmpty: typeof import('./src/components/ItsEmpty.vue')['default']
    JsonViewer: typeof import('./src/components/JsonViewer.vue')['default']
    'Ri:userLine': typeof import('~icons/ri/user-line')['default']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
  }
}
